/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppCloneVis {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppWeatherVis {
    }
}
declare global {
    interface HTMLAppCloneVisElement extends Components.AppCloneVis, HTMLStencilElement {
    }
    var HTMLAppCloneVisElement: {
        prototype: HTMLAppCloneVisElement;
        new (): HTMLAppCloneVisElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppWeatherVisElement extends Components.AppWeatherVis, HTMLStencilElement {
    }
    var HTMLAppWeatherVisElement: {
        prototype: HTMLAppWeatherVisElement;
        new (): HTMLAppWeatherVisElement;
    };
    interface HTMLElementTagNameMap {
        "app-clone-vis": HTMLAppCloneVisElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-weather-vis": HTMLAppWeatherVisElement;
    }
}
declare namespace LocalJSX {
    interface AppCloneVis {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppWeatherVis {
    }
    interface IntrinsicElements {
        "app-clone-vis": AppCloneVis;
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-weather-vis": AppWeatherVis;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-clone-vis": LocalJSX.AppCloneVis & JSXBase.HTMLAttributes<HTMLAppCloneVisElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-weather-vis": LocalJSX.AppWeatherVis & JSXBase.HTMLAttributes<HTMLAppWeatherVisElement>;
        }
    }
}
